QubesOS/qubes-hcl

- Qubes-HCL-Dell_Inc__________-Dell_System_XPS_L702X-20160609-013446.yml
used new version of tool due to QubesOS/qubes-issues#1994
> Add HCL report for Dell XPS L702X

- Lenovo-G505S-qmastery16.yml
all FixMe's already replaced with relevant information. See https://groups.google.com/d/msg/qubes-users/TS1zfKZ7q8w/JQFkVF4xBgAJ
> Add HCL report for Lenovo G505S (Coreboot-SeaBIOS)

- Qubes-HCL-LENOVO-20FQ005UGE-ypid.yml
Ref: https://groups.google.com/forum/#!msg/qubes-users/BQpFjqUgohs/3KvopyqvCAAJ
> Add HCL report for Lenovo Thinkpad X1 Yoga (20FQ005UGE) -- R3.1, R3.2

- ASUS-Q170M-C-ecneladis.yml
First one I'm uploading. :)
@andrewdavidwong I'll wait for you to check this before I PR the other new submissions.
> Add HCL report for ASUS-Q170M-C

- ASUS-Z97-PRO-Gamer-20170206-133838.yml
- ASUSTeK_COMPUTER_INC_-G750JW-20170130-125955.yml
- ASUSTeK_COMPUTER_INC_-GL752VW-20161207-142440.yml
- ASUSTeK_COMPUTER_INC_-UX303UA-20170126-144042.yml
- ASUSTeK_COMPUTER_INC_-UX305FA-20170212-084004.yml
- BIOSTAR_Group-MCP6P3-20170211-100639.yml
- Dell_Inc_-Inspiron_3520-20170130-220328.yml
- Dell_Inc_-Latitude_E7470-20170111-223321.yml
- Dell_Inc_-XPS_15_9550-20170108-222328.yml
- HP_EliteBook_8570p-20170114-125711.yml
- HP_Pavilion_Desktop_560_p0xx-20170213-212325.yml
- Hewlett_Packard-HP_Pavilion_dv6_Notebook_PC-20170120-085111.yml
- LENOVO-10HYS0NE00-20170114-185016.yml
- LENOVO-20FAS0AE00-20170214-180106.yml
- LENOVO-20H2S00700-20170214-113042.yml
- LENOVO-2985F4U-20170130-132918.yml
- LENOVO-688526G-20160305-133823.yml
- Lenovo-Thinkpad-T560-sboresch.yml
- Sony_Corporation-SVP11216PXB-20170210-145515.yml
ASUS Z97-Pro-gamer
BIOSTAR MCP6P3
Sony SVP11216PXB
> Add (18) HCL reports

- Qubes-HCL-LENOVO-20FQ005UGE-ypid.yml
~~Please wait with merging until I have posted on qubes-users and updated the link in this PR, thanks.~~
Ready.
> Test Qubes-HCL-LENOVO-20FQ005UGE with R4.0

- Qubes-HCL-Intel_R__Client_Systems-NUC10i7FNK-20200720-011247.yml
> NUC10i7FNK

- Gigabyte-GA-AX370-Gaming.yml
- Lenovo-IdeaPad_Y700-80NW-20201204-131856.yml
Hi @andrewdavidwong  these two came in today.
> new HCLs from 12/4/20

- ASUS-All_Series-20160830-115437.yml
- Dell-OptiPlex_790-20160322-212936.yml
- Dell-OptiPlex_790-20201220-035756.yml
- GPD-Win_Max-G1619_01-20200924-105918.yml
- Gigabyte-BRIX_Pro_-_Ultra_Compact_PC_(M4HM85P-00)-Bjarne_Thomsen.yml
- Hewlett-Packard-Laptop_15_dw2xxx-20201024-043033.yml
- Hewlett-Packard-Pavilion-20160730-185147.yml
- Intel-NUC7i5BNH-20171226-140508.yml
- Librem-15v2-20170429-164051.yml
- Purism-Librem_15-Todd_Weaver.yml
- System76-Meerkat-20160717-083155.yml
- VAIO-Z_VJZ131-20201108-105214.yml
@andrewdavidwong  ... a new one and a bit of clean up.
> New HCL from 12/20/20 and some minor fixes

- Dell-Latitude_7280-20181116-164644.yml
- Dell-Precision_5540-20210102-211604.yml
- Lenovo-ThinkBook_15_20SM-20201230-190834.yml
- add Lenovo ThinkBook 15 IIL & Dell Precision 5540
- update remark to Dell Latitude 7280: DELL TPM download link no longer works
> ThinkBook 15, Precision 5540 & update to Latitude 7280

- ASUS-All_Series-20160830-115437.yml
- ASUS-All_Series-20170304-205543.yml
- ASUS-All_Series-20210118-082645.yml
- Hewlett-Packard-ProBook_450_G7-20201223-080822.yml
- System76-Darter_Pro-20210117-224438.yml
- new HCLs from last two days
- some cosmetic changes to the model name of Asus All Series entires
- fixing chipset 'Comet Lake' in an old entry
> System76 Darter & Asus All Series HCLs

- Dell-Latitude_3330-20210219-205102.yml
> add Dell Latitude 3330 by Phil from 2/19/21

- Hewlett-Packard_ENVY_17m_bw0xxx-20210705-062022.yml
- update to existing entry as requested by reporter 'Del' aka '<djr>' aka '9thCat'
> 2021-07-17_new_HCLs

- Lenovo-ThinkPad_L380-qub411.yml
- Lenovo-ThinkPad_T470s-20NX000GMZ-20210810-145438.yml
- Purism-Librem_14-20210807-223750.yml
- Purism-Librem_14-20210816-094413.yml
- System76-Lemur_Pro-20210815-083057.yml
> 2021-08_16_new_HCLs

- Lenovo-ThinkPad_T14_Gen1-20S00044UK-20210826-140136.yml
- Lenovo-ThinkPad_X1_Carbon_9-20XW00A8US-20210828-183120.yml
- Librem-Mini-20210831-202930.yml
> 2021-08-31_new_HCLs

- Librem-Mini-20210831-202930.yml
- Purism-Librem_Mini-20210505-233313.yml
Based on [this comment](https://forum.qubes-os.org/t/hcl-librem-mini/6053/3).
> add 'v1' to the 'Librem Mini' entries

- Lenovo-ThinkPad_E14_Gen3-20YDCTO1WW-20210902-084441.yml
> 2021-09-03_new_HCLs

- Dell-Inspiron_1545-20170701-202426.yml
- Dell-Latitude_E6500-20180109-020259.yml
- Dell-Latitude_E7240-20210905-222744.yml
- Dell-Studio_XPS_1640-20170709-133934.yml
- Fujitsu-Lifebook_S762-20210905-014502.yml
- Fujitsu-Siemens-Esprimo_Mobile_M9410-20210823-051238.yml
- Lenovo-ThinkPad_S440-20AY001CAT-20210903-125731.yml
- Lenovo-ThinkPad_T400-6473PVU-20161225-025159.yml
- Lenovo-ThinkPad_X200-2024B53-20151023-214242.yml
- Lenovo-ThinkPad_X200-745434U-20151212-193925.yml
- Lenovo-ThinkPad_X200T-7449C4G-20160309-201439.yml
- Lenovo-ThinkPad_X200_7450B34-pakenham.yml
- Samsung-RV510-20170304-113851.yml
> 2021-09-05_new_HCLs

- MSI-MS_7977-20210906-005138.yml
> 2021-09-06_new_HCLs

- Acer-Predator_PH315-54-20230116-ful0n.yml
- Asus-ROG_Strix_B550-A_Gaming-20230107-rodfeher.yml
- Asus-ROG_Strix_GL704GW-20200330-173054.yml
- Lenovo-ThinkPad_E14-Gen2-20TA000DGE-20230122-190635.yml
- Lenovo-ThinkPad_L14_Gen2-21C5CTO1WW-20230114-152748.yml
- Lenovo-ThinkPad_P51-20HJS0BX00-20171215-110620.yml
- Star-Labs-StarBook-MK-VI-20230114-sheepskin.yml
Doing this as a pull request in the hopes to see error messages (testdeploy) and being able to fix things without bothering marek. Not sure I have the power to merge pull requests... but if I can commit directly, I should be able to merge too.
> HCL reports from 1/8/23 to 1/26/23
